export const TRENDING_MUSIC = [
  // --- AMAPIANO (15) ---
  { id: "ama1", category: "Amapiano", title: "Mnike", url: "/sounds/mnike.mp3", duration: "1:00" },
  { id: "ama2", category: "Amapiano", title: "Tshwala Bam", url: "/sounds/tshwala.mp3", duration: "0:31" },
    { id: "trust5", category: "Trust", title: "Minimalist Afro", url: "/sounds/minimal.mp3", duration: "1:00" },
  { id: "ama3", category: "Amapiano", title: "Water (Tyla)", url: "/sounds/water.mp3", duration: "0:17" },
  { id: "ama4", category: "Amapiano", title: "Awukhuzeki", url: "/sounds/awukhuzeki.mp3", duration: "1:00" },
  { id: "ama5", category: "Amapiano", title: "Iplan", url: "/sounds/iplan.mp3", duration: "0:28" },
  { id: "ama6", category: "Amapiano", title: "Funk 55", url: "/sounds/funk55.mp3", duration: "0:50" },
  { id: "ama7", category: "Amapiano", title: "Bhebha", url: "/sounds/bhebha.mp3", duration: "1:00" },
  { id: "ama8", category: "Amapiano", title: "Yaba Buluku", url: "/sounds/yababuluku.mp3", duration: "1:00" },
  { id: "ama9", category: "Amapiano", title: "Sgudi Snyc", url: "/sounds/sgudi.mp3", duration: "1:04" },
  { id: "ama10", category: "Amapiano", title: "Kilimanjaro", url: "/sounds/kilimanjaro.mp3", duration: "1:00" },
  { id: "ama13", category: "Amapiano", title: "Imizwilili", url: "/sounds/imizwilili.mp3", duration: "1:00" },
  { id: "ama14", category: "Amapiano", title: "Gangnam Style Piano", url: "/sounds/gangnamama.mp3", duration: "0:43" },
  { id: "ama15", category: "Amapiano", title: "Paris (Mlanjwen)", url: "/sounds/paris.mp3", duration: "1:00" },
  { id: "mot1", category: "Motivation", title: "Success Mindset", url: "/sounds/success.mp3", duration: "0:17" },
  { id: "mot2", category: "Motivation", title: "Last Last (Instrumental)", url: "/sounds/lastlast_inst.mp3", duration: "1:30" },
  { id: "mot3", category: "Motivation", title: "Victory Lap", url: "/sounds/victory.mp3", duration: "1:00" },
    { id: "lux1", category: "Lifestyle", title: "Tyla - Water (Chill)", url: "/sounds/water_chill.mp3", duration: "1:05" },
  { id: "lux3", category: "Lifestyle", title: "City Boys (Luxury Mix)", url: "/sounds/cityboys_luxe.mp3", duration: "0:57" },
  { id: "lux4", category: "Lifestyle", title: "Elegant Flow", url: "/sounds/elegant.mp3", duration: "1:00" },
{ id: "lux5", category: "Lifestyle", title: "Smooth Afro-Jazz", url: "/sounds/afrojazz.mp3", duration: "0:11" },

  // --- AFROBEATS (15) ---
  { id: "afro1", category: "Afrobeats", title: "City Boys", url: "/sounds/cityboys.mp3", duration: "0:25" },
  { id: "afro2", category: "Afrobeats", title: "Lonely At The Top", url: "/sounds/lonely.mp3", duration: "0:57" },
  { id: "afro3", category: "Afrobeats", title: "Cough (Odo)", url: "/sounds/cough.mp3", duration: "0:13" },
  { id: "afro4", category: "Afrobeats", title: "Reason", url: "/sounds/reason.mp3", duration: "0:56" },
  { id: "afro5", category: "Afrobeats", title: "Me & You", url: "/sounds/meyou.mp3", duration: "0:25" },
  { id: "afro6", category: "Afrobeats", title: "Unavailable", url: "/sounds/unavailable.mp3", duration: "0:20" },
  { id: "afro7", category: "Afrobeats", title: "Calm Down", url: "/sounds/calmdown.mp3", duration: "0:30" },
  { id: "afro8", category: "Afrobeats", title: "Last Last", url: "/sounds/lastlast.mp3", duration: "0:20" },
  { id: "afro9", category: "Afrobeats", title: "Rush (Ayra Starr)", url: "/sounds/rush.mp3", duration: "1:00" },
  { id: "afro10", category: "Afrobeats", title: "Buga", url: "/sounds/buga.mp3", duration: "1:00" },
  { id: "afro11", category: "Afrobeats", title: "Soweto", url: "/sounds/soweto.mp3", duration: "0:38" },
  { id: "afro12", category: "Afrobeats", title: "Bandana", url: "/sounds/bandana.mp3", duration: "0:56" },
  { id: "afro13", category: "Afrobeats", title: "People (Libianca)", url: "/sounds/people.mp3", duration: "0:55" },
  { id: "afro14", category: "Afrobeats", title: "Holiday", url: "/sounds/holiday.mp3", duration: "0:49" },
  { id: "afro15", category: "Afrobeats", title: "Charm", url: "/sounds/charm.mp3", duration: "1:00" },
  

  // --- DRILL / TRAP (10) ---
  { id: "drill1", category: "Drill", title: "Elon Musk", url: "/sounds/elonmusk.mp3", duration: "0:24" },
  { id: "drill2", category: "Drill", title: "Declan Rice", url: "/sounds/declan.mp3", duration: "1:01" },
  { id: "drill3", category: "Drill", title: "Who is Your Guy", url: "/sounds/guy.mp3", duration: "0:36" },
  { id: "drill4", category: "Drill", title: "Gyakie Drill", url: "/sounds/gyakie.mp3", duration: "0:20" },
  { id: "drill5", category: "Drill", title: "Black Sherif Kwaku", url: "/sounds/kwaku.mp3", duration: "0:20" },
  { id: "drill6", category: "Drill", title: "Dior", url: "/sounds/dior.mp3", duration: "0:25" },
  { id: "drill7", category: "Drill", title: "2:30", url: "/sounds/asake230.mp3", duration: "1:00" },
  { id: "drill8", category: "Drill", title: "Do I", url: "/sounds/doi.mp3", duration: "0:33" },
  { id: "drill9", category: "Drill", title: "Sittin' On Top", url: "/sounds/sittin.mp3", duration: "1:00" },
  { id: "drill10", category: "Drill", title: "Talibans", url: "/sounds/talibans.mp3", duration: "0:43" },

  // --- LOCAL / IVOIRE / CAMER (10) ---
  { id: "loc1", category: "Local", title: "Coup du Marteau", url: "/sounds/marteau.mp3", duration: "0:54" },
  { id: "loc2", category: "Local", title: "Zapata", url: "/sounds/zapata.mp3", duration: "0:38" },
  { id: "loc3", category: "Local", title: "En haut", url: "/sounds/enhaut.mp3", duration: "0:38" },
  { id: "loc4", category: "Local", title: "Mbolé Style", url: "/sounds/mbole.mp3", duration: "0:51" },
  { id: "loc5", category: "Local", title: "C'est doux", url: "/sounds/cdoux.mp3", duration: "0:34" },
  { id: "loc6", category: "Local", title: "Aicha Trembler", url: "/sounds/aicha.mp3", duration: "1:00" },
  { id: "loc7", category: "Local", title: "Azalaké", url: "/sounds/azalake.mp3", duration: "1:00" },
  { id: "loc8", category: "Local", title: "Commando", url: "/sounds/commando.mp3", duration: "0:37" },
  { id: "loc9", category: "Local", title: "Bikutsi Hit", url: "/sounds/bikutsi.mp3", duration: "0:59" },
  { id: "loc10", category: "Local", title: "Logobi 2024", url: "/sounds/logobi.mp3", duration: "0:59" },
  { id: "trust1", category: "Trust", title: "Professional Afro-Beat", url: "/sounds/biz_afro.mp3", duration: "0:23" },
];